server:
  host: "localhost"
  port: "8080"

db:
  host: "localhost"
  port: "5432"
  username: "db_user"
  dbname: "movielist"
  sslmode: "disable"

logger:
  loglevel: "debug"

token:
  signingKey: "gdajkl156alaflkj"
